// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfoCF7PPYr9jNn1Tqn7_dHXSXRxHRLSok',
    appId: '1:573833299511:web:1bd1c0a3fbcb0786b7a1b2',
    messagingSenderId: '573833299511',
    projectId: 'earthquake-tracker-71856',
    authDomain: 'earthquake-tracker-71856.firebaseapp.com',
    storageBucket: 'earthquake-tracker-71856.firebasestorage.app',
    measurementId: 'G-RWREP2NC0Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs6dtRKBt3KR7v_emxzrNu7HvRprHrlx0',
    appId: '1:573833299511:android:53eeb1ea64e30d7ab7a1b2',
    messagingSenderId: '573833299511',
    projectId: 'earthquake-tracker-71856',
    storageBucket: 'earthquake-tracker-71856.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHaZdyVTzN0_IUssrIuUaEb2JrCkB7LcM',
    appId: '1:573833299511:ios:a20fbab7e6569e1bb7a1b2',
    messagingSenderId: '573833299511',
    projectId: 'earthquake-tracker-71856',
    storageBucket: 'earthquake-tracker-71856.firebasestorage.app',
    iosBundleId: 'com.example.earthquakeTrackerr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHaZdyVTzN0_IUssrIuUaEb2JrCkB7LcM',
    appId: '1:573833299511:ios:a20fbab7e6569e1bb7a1b2',
    messagingSenderId: '573833299511',
    projectId: 'earthquake-tracker-71856',
    storageBucket: 'earthquake-tracker-71856.firebasestorage.app',
    iosBundleId: 'com.example.earthquakeTrackerr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfoCF7PPYr9jNn1Tqn7_dHXSXRxHRLSok',
    appId: '1:573833299511:web:adaa8de6cdfd5742b7a1b2',
    messagingSenderId: '573833299511',
    projectId: 'earthquake-tracker-71856',
    authDomain: 'earthquake-tracker-71856.firebaseapp.com',
    storageBucket: 'earthquake-tracker-71856.firebasestorage.app',
    measurementId: 'G-E0K9J2EG06',
  );
}
